### PR TITLE
Update simplify figure and benchmarks.

### PR DESCRIPTION
**Pull request by jeromekelleher**
simplify-results

### CODE REVIEW

**Comment by ashander** [comment]
LGTM. Except panel labels of the sort shown here https://stackoverflow.com/a/18346779/4598520 (outside  upper left corner of the panel) look better to me

**Comment by ashander** [comment]
Oh and in #20 you'd mentioned putting more lines on (A) but I don't think that's necessary for now

**Comment by jeromekelleher** [comment]
> LGTM. Except panel labels of the sort shown here https://stackoverflow.com/a/18346779/4598520 (outside upper left corner of the panel) look better to me

I agree... the journal will change these anyway though, most likely, so there's not much point in getting too deep into it. Easiest to just keep it simple for now.

> Oh and in #20 you'd mentioned putting more lines on (A) but I don't think that's necessary for now

(A) looks good to me now. We're seeing the variance pretty clearly, and the mean is also pretty obvious. No point in putting too many lines on I think.

**Comment by ashander** [comment]
Sounds good for both.

On the labels that's very true about production. I googled mostly b/c I was
curious how hard it is to do such labels in pyplot or whatever. In R I'm
spoiled by
https://cran.r-project.org/web/packages/cowplot/vignettes/introduction.html

**Comment by petrelharp** [comment]
nice, thanks for fixing up my hack-ey figures.

**Pull request merged**
